# Generated by Django 4.2.20 on 2025-09-13 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0004_remove_section_professor_section_professors"),
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("GROUP", "Actividad Grupal"),
                            ("INDIVIDUAL", "Actividad Individual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Instrucciones detalladas para la actividad"
                    ),
                ),
                ("due_date", models.DateTimeField()),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=100, help_text="Puntos totales de la actividad"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="academic.course",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"role": "PROFESOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="academic.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="artifact",
            options={"verbose_name": "Artefacto", "verbose_name_plural": "Artefactos"},
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={
                "verbose_name": "Portafolio",
                "verbose_name_plural": "Portafolios",
            },
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="portfolio",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to="academic.course",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to="academic.section",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "ALUMNO"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("student", "course", "section")},
        ),
        migrations.CreateModel(
            name="ActivityAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "submission_notes",
                    models.TextField(
                        blank=True, help_text="Notas del estudiante sobre su entrega"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="portfolios.activity",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_assignments",
                        to="portfolios.portfolio",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "ALUMNO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Actividad",
                "verbose_name_plural": "Asignaciones de Actividades",
                "unique_together": {("activity", "student")},
            },
        ),
        migrations.AddField(
            model_name="artifact",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="portfolios.activityassignment",
            ),
        ),
    ]
