# Generated by Django 4.2.20 on 2025-09-13 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0004_remove_section_professor_section_professors"),
        ("portfolios", "0002_activity_alter_artifact_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("student", "section")},
        ),
    ]
