# Generated by Django 4.2.20 on 2025-09-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_course_professor"),
        ("portfolios", "0003_alter_portfolio_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_courses",
                        to="academic.course",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso del Portafolio",
                "verbose_name_plural": "Cursos del Portafolio",
                "unique_together": {("portfolio", "course")},
            },
        ),
    ]
