# Generated by Django 4.2.20 on 2025-09-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MATEMATICAS", "Matemáticas"),
                    ("CIENCIAS", "Ciencias Naturales"),
                    ("LENGUAJE", "Lenguaje y Literatura"),
                    ("HISTORIA", "Historia y Geografía"),
                    ("EDUCACION_FISICA", "Educación Física"),
                    ("ARTES", "Artes"),
                    ("MUSICA", "Música"),
                    ("TECNOLOGIA", "Tecnología"),
                    ("INGLES", "Inglés"),
                    ("FRANCES", "Francés"),
                    ("FILOSOFIA", "Filosofía"),
                    ("PSICOLOGIA", "Psicología"),
                    ("ADMINISTRACION", "Administración"),
                    ("CONTABILIDAD", "Contabilidad"),
                    ("INFORMATICA", "Informática"),
                    ("OTRO", "Otro"),
                ],
                help_text="Especialidad del profesor",
                max_length=30,
                null=True,
            ),
        ),
    ]
