# Generated by Django 4.2.20 on 2025-09-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_content_generator", "0002_auto_20250913_0035"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generationrequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sourcedocument",
            name="uploaded_by",
        ),
        migrations.DeleteModel(
            name="Chunk",
        ),
        migrations.DeleteModel(
            name="GenerationRequest",
        ),
        migrations.DeleteModel(
            name="SourceDocument",
        ),
    ]
