# Generated by Django 4.2.20 on 2025-09-13 06:01

import ai_content_generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_content_generator", "0003_remove_generationrequest_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="session_id",
            field=models.CharField(
                default=ai_content_generator.models.generate_session_id,
                max_length=100,
                unique=True,
            ),
        ),
    ]
