# Generated by Django 4.2.20 on 2025-09-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_content_generator", "0004_alter_conversation_session_id"),
    ]

    operations = [
        # Primero eliminar la tabla antigua
        migrations.DeleteModel(
            name="GeneratedContent",
        ),
        # Crear la nueva tabla con la estructura correcta
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("html_content", models.TextField()),
                ("css_content", models.TextField()),
                ("js_content", models.TextField()),
                ("grapesjs_components", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="generated_content", to="ai_content_generator.conversation")),
            ],
            options={
                "verbose_name": "Contenido Generado",
                "verbose_name_plural": "Contenidos Generados",
                "ordering": ["-created_at"],
            },
        ),
    ]
