# Generated by Django 4.2.24 on 2025-09-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content_generator', '0005_auto_20250913_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to='ai_content_generator.conversation'),
        ),
    ]
