# Generated by Django 4.2.24 on 2025-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content_generator', '0007_add_gamma_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttemplate',
            name='grapesjs_config',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='css_content',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='grapesjs_components',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='js_content',
        ),
        migrations.AlterField(
            model_name='generatedcontent',
            name='content_type',
            field=models.CharField(choices=[('gamma', 'Gamma Blocks')], default='gamma', max_length=50),
        ),
    ]
