# Generated by Django 4.2.20 on 2025-09-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institutions.gradelevel",
            ),
        ),
    ]
