# Generated by Django 4.2.20 on 2025-09-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_section_grade_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="academic.course",
            ),
        ),
    ]
