# Generated by Django 4.2.20 on 2025-09-12 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0003_alter_section_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="professor",
        ),
        migrations.AddField(
            model_name="section",
            name="professors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "PROFESOR"},
                related_name="sections_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
