# Generated by Django 4.2.20 on 2025-09-13 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0004_remove_section_professor_section_professors"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "PROFESOR"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
