# Generated by Django 4.2.20 on 2025-09-13 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0007_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Documento"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio"),
                            ("IMAGE", "Imagen"),
                            ("LINK", "Enlace"),
                            ("OTHER", "Otro"),
                        ],
                        default="DOCUMENT",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="materials/"),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "is_shared",
                    models.BooleanField(
                        default=True,
                        help_text="True = material de clase, False = personalizado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_students",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Estudiantes específicos para materiales personalizados",
                        limit_choices_to={"role": "ALUMNO"},
                        related_name="assigned_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"role": "PROFESOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academic.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiales",
                "ordering": ["-created_at"],
            },
        ),
    ]
