# Generated by Django 4.2.20 on 2025-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0008_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="content",
            field=models.TextField(
                blank=True, help_text="Contenido generado por IA", null=True
            ),
        ),
    ]
