# Generated by Django 4.2.20 on 2025-09-14 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0009_material_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="content",
        ),
        migrations.CreateModel(
            name="MaterialViewingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Duración total en segundos"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Si el estudiante completó la visualización",
                    ),
                ),
                (
                    "progress_percentage",
                    models.FloatField(
                        default=0.0, help_text="Porcentaje de progreso (0-100)"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actividad registrada"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewing_sessions",
                        to="academic.material",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "ALUMNO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_viewing_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Visualización",
                "verbose_name_plural": "Sesiones de Visualización",
                "ordering": ["-started_at"],
                "unique_together": {("student", "material", "started_at")},
            },
        ),
        migrations.CreateModel(
            name="MaterialInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("PLAY", "Reproducir"),
                            ("PAUSE", "Pausar"),
                            ("SEEK", "Buscar"),
                            ("DOWNLOAD", "Descargar"),
                            ("COMPLETE", "Completar"),
                            ("ABANDON", "Abandonar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales como posición de video, etc.",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="academic.materialviewingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interacción con Material",
                "verbose_name_plural": "Interacciones con Materiales",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MaterialAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("unique_viewers", models.PositiveIntegerField(default=0)),
                (
                    "total_duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Duración total en segundos"
                    ),
                ),
                (
                    "average_duration",
                    models.FloatField(
                        default=0.0, help_text="Duración promedio en segundos"
                    ),
                ),
                (
                    "completion_rate",
                    models.FloatField(
                        default=0.0, help_text="Tasa de finalización (0-100)"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="academic.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analítica de Material",
                "verbose_name_plural": "Analíticas de Materiales",
            },
        ),
    ]
