# Generated by Django 4.2.20 on 2025-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0010_remove_material_content_materialviewingsession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("DOCUMENT", "Documento"),
                    ("VIDEO", "Video"),
                    ("AUDIO", "Audio"),
                    ("IMAGE", "Imagen"),
                    ("LINK", "Enlace"),
                    ("SCORM", "SCORM"),
                    ("OTHER", "Otro"),
                ],
                default="DOCUMENT",
                max_length=20,
            ),
        ),
    ]
