# Generated by Django 4.2.20 on 2025-09-14 18:01

from django.db import migrations


def update_scorm_materials(apps, schema_editor):
    """Actualiza todos los materiales SCORM para que tengan el tipo correcto"""
    Material = apps.get_model('academic', 'Material')
    
    # Buscar materiales que tengan archivos SCORM pero tipo DOCUMENT
    scorm_materials = Material.objects.filter(
        file__icontains='scorm',
        material_type='DOCUMENT'
    )
    
    print(f"Actualizando {scorm_materials.count()} materiales SCORM...")
    
    # Actualizar el tipo de material
    for material in scorm_materials:
        material.material_type = 'SCORM'
        material.save()
        print(f"Actualizado: {material.name} -> SCORM")
    
    print("Materiales SCORM actualizados correctamente")


def reverse_update_scorm_materials(apps, schema_editor):
    """Revertir la actualización (opcional)"""
    Material = apps.get_model('academic', 'Material')
    
    # Revertir materiales SCORM a DOCUMENT
    scorm_materials = Material.objects.filter(
        file__icontains='scorm',
        material_type='SCORM'
    )
    
    for material in scorm_materials:
        material.material_type = 'DOCUMENT'
        material.save()


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0011_alter_material_material_type"),
    ]

    operations = [
        migrations.RunPython(update_scorm_materials, reverse_update_scorm_materials),
    ]
