# Generated by Django 4.2.20 on 2025-09-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0012_update_scorm_materials"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="content_data",
            field=models.JSONField(
                blank=True,
                help_text="Contenido generado por IA almacenado como JSON",
                null=True,
            ),
        ),
    ]
